apiVersion: v1
kind: Service
metadata:
  name: oficina-api
  namespace: oficina
  labels:
    app: oficina-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - __VPC_CIDR_BLOCK__
  selector:
    app: oficina-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
